name: NametagEdit
main: com.nametagedit.plugin.NametagEdit
version: 4.5.0
authors: [sgtcaze, Cory]
soft-depend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds]
commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]
