name: NametagEdit
main: com.nametagedit.plugin.NametagEdit
version: 4.4.16
authors: [sgtcaze, Cory]
softdepend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]
commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]
