name: NametagEdit
main: com.nametagedit.plugin.NametagEdit
version: 4.1.3
authors: [sgtcaze, Cory]
soft-depend: [zPermissions, PermissionsEX, GroupManager, LibsDisguises]
commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]